# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-garuda"
BBFILE_PATTERN_meta-garuda = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-garuda = "6"

LAYERDEPENDS_meta-garuda = "core"
LAYERSERIES_COMPAT_meta-garuda = "scarthgap"
