name: Project Garuda Docker CI

on: [push, pull_request]

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run:  docker build -t garuda-ci .

    - name: Run unit tests inside container
      # By adding './run_tests' at the end, we override the default CMD
      run:  docker run --rm garuda-ci ./run_tests
